[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day18"
path = "src/main.rs"

[dependencies]
color-eyre = "0.6.2"
criterion = "0.5.1"
itertools = "0.11.0"
rustc-hash = "1.1.0"

[[bench]]
name = "runtime"
harness = false
