[package]
name = "day17"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day17"
path = "src/main.rs"

[dependencies]
color-eyre = "0.6.2"

[dev_dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "runtime"
harness = false
