[package]
name = "day17"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day17"
path = "src/main.rs"

[dependencies]
ahash = "0.8.3"
color-eyre = "0.6.2"
criterion = { version = "0.5.1", features = ["html_reports"] }
itertools = "0.11.0"

[[bench]]
name = "runtime"
harness = false
