[package]
name = "day23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_ops = "0.3.0"
color-eyre = "0.6.2"
counter = "0.5.7"
fxhash = "0.2.1"
itertools = "0.11.0"
